name: test
on:
  push:
    branches:
      '*'
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        raku-version:
          - "latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install download configurator
        run: wget -O .zef-configurator https://raw.githubusercontent.com/elerille/micro/main/bin/raku-micro
      - name: Install deps
        run: |
          zef upgrade zef
          zef install JSON::Fast
          raku .zef-configurator configure .zef-conf.json
      - name: Test
        run: zef --config-path=.zef-conf.json install .

